# history file { ---------------------------------------------------------------
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory extendedglob
zstyle :compinstall filename '/home/cataldo/.zshrc'
# history file } ---------------------------------------------------------------

# path { -----------------------------------------------------------------------
fpath=(
    ~/.zscripts
    "${fpath[@]}"
)
path+=('/usr/local/texlive/2019/bin/x86_64-linux')
# path } -----------------------------------------------------------------------

# autocomplete { ---------------------------------------------------------------
autoload -Uz compinit promptinit
compinit
promptinit
setopt COMPLETE_ALIASES
# autocomplete } ---------------------------------------------------------------

# theme { ----------------------------------------------------------------------
prompt adam2
# theme } ----------------------------------------------------------------------

# vi mode { --------------------------------------------------------------------
bindkey -v
export KEYTIMEOUT=5
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line
# vi mode } --------------------------------------------------------------------

# dirstack, use cd - { ---------------------------------------------------------
DIRSTACKFILE="$HOME/.cache/zsh/dirs"
if [[ -f $DIRSTACKFILE ]] && [[ $#dirstack -eq 0 ]]; then
	dirstack=( ${(f)"$(< $DIRSTACKFILE)"} )
	[[ -d $dirstack[1] ]] && cd $dirstack[1]
fi

chpwd() {
  print -l $PWD ${(u)dirstack} >$DIRSTACKFILE
}

DIRSTACKSIZE=20
setopt AUTO_PUSHD PUSHD_SILENT PUSHD_TO_HOME
## Remove duplicate entries
setopt PUSHD_IGNORE_DUPS
## This reverts the +/- operators.
setopt PUSHD_MINUS
# dirstack, use cd - } ---------------------------------------------------------


# aliases { --------------------------------------------------------------------
alias ls='ls --color=auto --group-directories-first -F'
alias ..='cd ..'
alias tmux='tmux -2'
. $HOME/.zsh/plugins/bd/bd.zsh
# aliases } --------------------------------------------------------------------
